<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Stock;

class StocksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       
            Stock::create(["symbol"=> "AZUL4", "name"=> "AZUL SA"]);
            Stock::create(["symbol"=> "GOLL4", "name"=> "GOL LINHAS AEREAS"]);
             Stock::create(["symbol"=> "CEPE3", "name"=> "CIA ENERGETICA DE PERNAMBUCO"]);
             Stock::create(["symbol"=> "LAME3", "name"=> "LOJAS AMERICANAS SA"]);
             Stock::create(["symbol"=> "LAME4", "name"=> "LOJAS AMERICANAS SA PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "ALSO3", "name"=> "ALIANSCE SONAE SHOPPING CENT"]);
             Stock::create(["symbol"=> "OPCT3", "name"=> "OCEANPACT SERVICOS MARITIMOS"]);
             Stock::create(["symbol"=> "ESTR3", "name"=> "MANUF BRINQUEDOS ESTRELA SA"]);
             Stock::create(["symbol"=> "BMKS3", "name"=> "BICICLETAS MONARK SA"]);
             Stock::create(["symbol"=> "EQPA3", "name"=> "EQUATORIAL PARA DISTRIBUIDOR"]);
             Stock::create(["symbol"=> "NORD3", "name"=> "NORDON INDUS METALURGICA SA"]);
             Stock::create(["symbol"=> "TIET11", "name"=> "AES TIETE ENERGIA SA-UNIT"]);
             Stock::create(["symbol"=> "IGBR3", "name"=> "IGB ELETRONICA SA"]);
             Stock::create(["symbol"=> "JFEN3", "name"=> "JOAO FORTES ENGENHARIA S.A."]);
             Stock::create(["symbol"=> "ROMI3", "name"=> "INDUSTRIAS ROMI SA"]);
             Stock::create(["symbol"=> "ECOR3", "name"=> "ECORODOVIAS INFRA E LOG SA"]);
             Stock::create(["symbol"=> "TIET3", "name"=> "AES TIETE ENERGIA SA"]);
             Stock::create(["symbol"=> "PRIO3", "name"=> "PETRO RIO SA"]);
             Stock::create(["symbol"=> "ITSA3", "name"=> "ITAUSA SA"]);
             Stock::create(["symbol"=> "ITSA4", "name"=> "ITAUSA SA PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "RENT3", "name"=> "LOCALIZA RENT A CAR"]);
             Stock::create(["symbol"=> "LUXM3", "name"=> "TREVISA INVESTIMENTOS SA"]);
             Stock::create(["symbol"=> "LOGG3", "name"=> "LOG COMMERCIAL PROPERTIES E"]);
             Stock::create(["symbol"=> "ENGI11", "name"=> "ENERGISA SA-UNITS"]);
             Stock::create(["symbol"=> "CIEL3", "name"=> "CIELO SA"]);
             Stock::create(["symbol"=> "JSLG3", "name"=> "JSL SA"]);
             Stock::create(["symbol"=> "B3SA3", "name"=> "B3 SA-BRASIL BOLSA BALCAO"]);
             Stock::create(["symbol"=> "PTBL3", "name"=> "PORTOBELLO SA"]);
             Stock::create(["symbol"=> "WHRL3", "name"=> "WHIRLPOOL SA"]);
             Stock::create(["symbol"=> "TAEE11", "name"=> "TRANSMISSORA ALIANCA DE-UNIT"]);
             Stock::create(["symbol"=> "ABEV3", "name"=> "AMBEV SA"]);
             Stock::create(["symbol"=> "TEKA3", "name"=> "TEKA-TECELAGEM KUEHNRICH SA"]);
             Stock::create(["symbol"=> "CRFB3", "name"=> "ATACADAO SA"]);
             Stock::create(["symbol"=> "BRML3", "name"=> "BR MALLS PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "GOAU3", "name"=> "METALURGICA GERDAU SA"]);
             Stock::create(["symbol"=> "GOAU4", "name"=> "METALURGICA GERDAU SA PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "VLID3", "name"=> "VALID SOLUCOES SA"]);
             Stock::create(["symbol"=> "MULT3", "name"=> "MULTIPLAN EMPREENDIMENTOS"]);
             Stock::create(["symbol"=> "TPIS3", "name"=> "TPI - TRIUNFO PARTICIPACOES"]);
             Stock::create(["symbol"=> "ENGI3", "name"=> "ENERGISA S.A."]);
             Stock::create(["symbol"=> "MNDL3", "name"=> "MUNDIAL SA PROD DE CONSUMO"]);
             Stock::create(["symbol"=> "NEMO3", "name"=> "SUZANO HOLDING SA"]);
             Stock::create(["symbol"=> "BDLL3", "name"=> "BARDELLA SA INDUSTRIAS MECAN"]);
             Stock::create(["symbol"=> "FLRY3", "name"=> "FLEURY SA"]);
             Stock::create(["symbol"=> "REDE3", "name"=> "REDE ENERGIA SA"]);
             Stock::create(["symbol"=> "EALT3", "name"=> "ELECTRO ACO ALTONA SA"]);
             Stock::create(["symbol"=> "ALPK3", "name"=> "ALLPARK EMPREENDIMENTOS PART"]);
             Stock::create(["symbol"=> "SHOW3", "name"=> "T4F ENTRETENIMENTO SA"]);
             Stock::create(["symbol"=> "CTSA3", "name"=> "CIA TECIDOS SANTANENSE"]);
             Stock::create(["symbol"=> "FESA3", "name"=> "FERBASA-FERRO LIGAS DA BAHIA"]);
             Stock::create(["symbol"=> "INTB3", "name"=> "INTELBRAS SA INDUSTRIA DE TE"]);
             Stock::create(["symbol"=> "TCNO3", "name"=> "TECNOSOLO ENGENHARIA SA"]);
             Stock::create(["symbol"=> "BSEV3", "name"=> "BIOSEV SA"]);
             Stock::create(["symbol"=> "GFSA3", "name"=> "GAFISA SA"]);
             Stock::create(["symbol"=> "PEAB3", "name"=> "CIA PARTICIP ALIANCA BAHIA"]);
             Stock::create(["symbol"=> "PATI3", "name"=> "PANATLANTICA SA"]);
             Stock::create(["symbol"=> "OSXB3", "name"=> "OSX BRASIL SA"]);
             Stock::create(["symbol"=> "HBRE3", "name"=> "HBR REALTY EMPREENDIMENTOS I"]);
             Stock::create(["symbol"=> "PNVL3", "name"=> "DIMED SA DISTRIBUIDORA DE ME"]);
             Stock::create(["symbol"=> "OFSA3", "name"=> "OURO FINO SAUDE ANIMAL PARTI"]);
             Stock::create(["symbol"=> "LLIS3", "name"=> "RESTOQUE COMERCIO E CONFEC"]);
             Stock::create(["symbol"=> "CAMB3", "name"=> "CAMBUCI S.A."]);
             Stock::create(["symbol"=> "AMBP3", "name"=> "AMBIPAR PARTICIPACOES E EMPR"]);
             Stock::create(["symbol"=> "HGTX3", "name"=> "CIA HERING"]);
             Stock::create(["symbol"=> "JOPA3", "name"=> "JOAQUIM OLIVEIRA S.A.-PARTIC"]);
             Stock::create(["symbol"=> "BBSD11", "name"=> "BB ETF S&P DIVIDENDOS BRASIL"]);
             Stock::create(["symbol"=> "BEES3", "name"=> "BANESTES SA-BANCO ESTADO ESP"]);
             Stock::create(["symbol"=> "GSHP3", "name"=> "GENERAL SHOPPING E OUTLETS D"]);
             Stock::create(["symbol"=> "GPAR3", "name"=> "CIA CELG DE PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "CPLE3", "name"=> "CIA PARANAENSE DE ENERGIA"]);
             Stock::create(["symbol"=> "CMIN3", "name"=> "CSN MINERACAO SA"]);
             Stock::create(["symbol"=> "CCRO3", "name"=> "CCR SA"]);
             Stock::create(["symbol"=> "ALUP11", "name"=> "ALUPAR INVESTIMENTO SA-UNIT"]);
             Stock::create(["symbol"=> "CASH3", "name"=> "MELIUZ SA - ON"]);
             Stock::create(["symbol"=> "ARZZ3", "name"=> "AREZZO INDUSTRIA E COMERCIO"]);
             Stock::create(["symbol"=> "LINX3", "name"=> "LINX SA"]);
             Stock::create(["symbol"=> "BRGE3", "name"=> "CONSORCIO ALFA DE ADMINIST"]);
             Stock::create(["symbol"=> "NGRD3", "name"=> "NEOGRID PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "SULA11", "name"=> "SUL AMERICA SA - UNITS"]);
             Stock::create(["symbol"=> "AALR3", "name"=> "CENTRO DE IMAGEM DIAGNOSTICO"]);
             Stock::create(["symbol"=> "JPSA3", "name"=> "JEREISSATI PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "USIM3", "name"=> "USINAS SIDERURGICAS DE MINAS"]);
             Stock::create(["symbol"=> "USIM5", "name"=> "USINAS SIDERURGICAS DE MINAS PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "CVCB3", "name"=> "CVC BRASIL OPERADORA E AGENC"]);
             Stock::create(["symbol"=> "HAPV3", "name"=> "HAPVIDA PARTICIPACOES E INVE"]);
             Stock::create(["symbol"=> "YDUQ3", "name"=> "YDUQS PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "TRPL3", "name"=> "CIA DE TRANSMISSAO DE ENERGI"]);
             Stock::create(["symbol"=> "PIBB11", "name"=> "IT NOW PIBB IBRX-50 FI"]);
             Stock::create(["symbol"=> "BAHI3", "name"=> "BAHEMA SA"]);
             Stock::create(["symbol"=> "CRDE3", "name"=> "CR2 EMPREENDIMENTOS IMOBILIA"]);
             Stock::create(["symbol"=> "JBSS3", "name"=> "JBS SA"]);
             Stock::create(["symbol"=> "MILS3", "name"=> "MILLS ESTRUTURAS E SERVICOS"]);
             Stock::create(["symbol"=> "LCAM3", "name"=> "COMPANHIA DE LOCACAO DAS AME"]);
             Stock::create(["symbol"=> "EGIE3", "name"=> "ENGIE BRASIL ENERGIA SA"]);
             Stock::create(["symbol"=> "HYPE3", "name"=> "HYPERA SA"]);
             Stock::create(["symbol"=> "CBEE3", "name"=> "AMPLA ENERGIA E SERVICOS SA"]);
             Stock::create(["symbol"=> "DTEX3", "name"=> "DURATEX SA"]);
             Stock::create(["symbol"=> "MAPT3", "name"=> "CEMEPE INVESTIMENTOS S.A."]);
             Stock::create(["symbol"=> "BRIV3", "name"=> "BANCO ALFA DE INVESTIMENTO"]);
             Stock::create(["symbol"=> "BIOM3", "name"=> "BIOMM SA"]);
             Stock::create(["symbol"=> "DOHL3", "name"=> "DOHLER SA COMERCIO E INDUSTR"]);
             Stock::create(["symbol"=> "LIGT3", "name"=> "LIGHT SA"]);
             Stock::create(["symbol"=> "VVAR3", "name"=> "VIA VAREJO SA"]);
             Stock::create(["symbol"=> "TOTS3", "name"=> "TOTVS SA"]);
             Stock::create(["symbol"=> "BBSE3", "name"=> "BB SEGURIDADE PARTICIPACOES"]);
             Stock::create(["symbol"=> "LPSB3", "name"=> "LPS BRASIL CONS DE IMOVEIS"]);
             Stock::create(["symbol"=> "TKNO3", "name"=> "TEKNO SA INDUSTRIA E COMERCI"]);
             Stock::create(["symbol"=> "CEEB3", "name"=> "CIA ELETRICIDADE DA BAHIA"]);
             Stock::create(["symbol"=> "EEEL3", "name"=> "CIA ESTADUAL DE GERACAO E TR"]);
             Stock::create(["symbol"=> "BPAC3", "name"=> "BANCO BTG PACTUAL SA"]);
             Stock::create(["symbol"=> "AHEB3", "name"=> "SAO PAULO TURISMO SA"]);
             Stock::create(["symbol"=> "SOMA3", "name"=> "GRUPO DE MODA SOMA SA"]);
             Stock::create(["symbol"=> "SGPS3", "name"=> "SPRINGS GLOBAL PARTICIPACOES"]);
             Stock::create(["symbol"=> "SIMH3", "name"=> "SIMPAR SA"]);
             Stock::create(["symbol"=> "CNSY3", "name"=> "CINESYSTEM SA"]);
             Stock::create(["symbol"=> "GGBR3", "name"=> "GERDAU S.A."]);
             Stock::create(["symbol"=> "GGBR4", "name"=> "GERDAU S.A. PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "ENMT3", "name"=> "ENERGISA MATO GROSSO DISTRIB"]);
             Stock::create(["symbol"=> "TELB3", "name"=> "TELECOMUNIC BRASILEIRAS S.A."]);
             Stock::create(["symbol"=> "CEGR3", "name"=> "CIA DISTRIBUIDORA DE GAS"]);
             Stock::create(["symbol"=> "CGAS3", "name"=> "CIA DE GAS DE SAO PAULO"]);
             Stock::create(["symbol"=> "CATA3", "name"=> "CIA INDUSTRIAL CATAGUASES"]);
             Stock::create(["symbol"=> "PSSA3", "name"=> "PORTO SEGURO SA"]);
             Stock::create(["symbol"=> "ESPA3", "name"=> "MPM CORPOREOS SA"]);
             Stock::create(["symbol"=> "TASA3", "name"=> "TAURUS ARMAS"]);
             Stock::create(["symbol"=> "GNDI3", "name"=> "NOTRE DAME INTERMED PAR SA"]);
             Stock::create(["symbol"=> "WEST3", "name"=> "WESTWING COMERCIO VAREJISTA"]);
             Stock::create(["symbol"=> "BRFS3", "name"=> "BRF SA"]);
             Stock::create(["symbol"=> "ELMD3", "name"=> "ELETROMIDIA SA"]);
             Stock::create(["symbol"=> "BEEF3", "name"=> "MINERVA SA"]);
             Stock::create(["symbol"=> "CURY3", "name"=> "CURY CONSTRUTORA E INCORPORA"]);
             Stock::create(["symbol"=> "MTRE3", "name"=> "MITRE REALTY EMPREENDIMENTOS"]);
             Stock::create(["symbol"=> "PRNR3", "name"=> "PRINER SERVICOS INDUSTRIAIS"]);
             Stock::create(["symbol"=> "MELK3", "name"=> "MELNICK EVEN DESENVOLVIMENTO"]);
             Stock::create(["symbol"=> "SLCE3", "name"=> "SLC AGRICOLA SA"]);
             Stock::create(["symbol"=> "BBRK3", "name"=> "BRASIL BROKERS PARTICIPACOES"]);
             Stock::create(["symbol"=> "GOVE11", "name"=> "IT NOW IGCT FUNDO DE INDICE"]);
             Stock::create(["symbol"=> "BRPR3", "name"=> "BR PROPERTIES SA"]);
             Stock::create(["symbol"=> "EMBR3", "name"=> "EMBRAER SA"]);
             Stock::create(["symbol"=> "SUZB3", "name"=> "SUZANO SA"]);
             Stock::create(["symbol"=> "BBDC3", "name"=> "BANCO BRADESCO S.A."]);
             Stock::create(["symbol"=> "BBDC4", "name"=> "BANCO BRADESCO S.A. PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "DASA3", "name"=> "DIAGNOSTICOS DA AMERICA SA"]);
             Stock::create(["symbol"=> "CEED3", "name"=> "CIA ESTADUAL DE DISTRIBUICAO"]);
             Stock::create(["symbol"=> "ELET3", "name"=> "CENTRAIS ELETRICAS BRASILIER"]);
             Stock::create(["symbol"=> "ELET6", "name"=> "CENTRAIS ELETRICAS BRASILIER PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "SMAC11", "name"=> "IT NOW ETF SMLL"]);
             Stock::create(["symbol"=> "NEOE3", "name"=> "NEOENERGIA SA"]);
             Stock::create(["symbol"=> "PFRM3", "name"=> "PROFARMA DISTRIBUIDORA"]);
             Stock::create(["symbol"=> "CTNM3", "name"=> "CIA TECIDOS NORTE DE MINAS"]);
             Stock::create(["symbol"=> "BMIN3", "name"=> "BANCO MERCANTIL DE INVESTIME"]);
             Stock::create(["symbol"=> "PSVM11", "name"=> "PORTO SUDESTE VM SA"]);
             Stock::create(["symbol"=> "CCPR3", "name"=> "CYRELA COMMERCIAL PROPERTIES"]);
             Stock::create(["symbol"=> "CEDO3", "name"=> "CIA DE FIACAO E TECIDOS CEDR"]);
             Stock::create(["symbol"=> "HETA3", "name"=> "HERCULES SA FABRICA TALHERES"]);
             Stock::create(["symbol"=> "CLSC3", "name"=> "CENTRAIS ELETRICA STA CATARI"]);
             Stock::create(["symbol"=> "ETER3", "name"=> "ETERNIT SA"]);
             Stock::create(["symbol"=> "AFLT3", "name"=> "AFLUENTE TRANSMISSAO DE"]);
             Stock::create(["symbol"=> "EKTR3", "name"=> "ELEKTRO REDES SA"]);
             Stock::create(["symbol"=> "AMAR3", "name"=> "MARISA LOJAS SA"]);
             Stock::create(["symbol"=> "FRIO3", "name"=> "METALFRIO SOLUTIONS SA"]);
             Stock::create(["symbol"=> "SAPR11", "name"=> "CIA DE SANEAMENTO DO PA-UNIT"]);
             Stock::create(["symbol"=> "NUTR3", "name"=> "NUTRIPLANT INDUSTRIA E COMER"]);
             Stock::create(["symbol"=> "FRTA3", "name"=> "POMIFRUTAS SA"]);
             Stock::create(["symbol"=> "SMAL11", "name"=> "ISHARES BM&FBOVESPA SM CAP"]);
             Stock::create(["symbol"=> "VIVR3", "name"=> "VIVER INCORPORADORA E CONSTR"]);
             Stock::create(["symbol"=> "UGPA3", "name"=> "ULTRAPAR PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "BOVV11", "name"=> "IT NOW IBOVESPA FUNDO INDICE"]);
             Stock::create(["symbol"=> "BPAC12", "name"=> "BANCO BTG PACTUAL SA PNA-RCP"]);
             Stock::create(["symbol"=> "XFIX11", "name"=> "TREND ETF IFIX"]);
             Stock::create(["symbol"=> "IMAB11", "name"=> "IT NOW ID ETF IMA-B"]);
             Stock::create(["symbol"=> "RSUL3", "name"=> "METALURGICA RIOSULENSE S.A."]);
             Stock::create(["symbol"=> "IRBR3", "name"=> "IRB BRASIL RESSEGUROS SA"]);
             Stock::create(["symbol"=> "EQTL3", "name"=> "EQUATORIAL ENERGIA SA - ORD"]);
             Stock::create(["symbol"=> "VALE3", "name"=> "VALE SA"]);
             Stock::create(["symbol"=> "HOOT3", "name"=> "HOTEIS OTHON S.A."]);
             Stock::create(["symbol"=> "ATOM3", "name"=> "ATOM PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "CARD3", "name"=> "CSU CARDSYSTEM SA"]);
             Stock::create(["symbol"=> "CMIG3", "name"=> "CIA ENERGETICA DE MINAS GER"]);
             Stock::create(["symbol"=> "CMIG4", "name"=> "CIA ENERGETICA DE MINAS GER PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "TAEE3", "name"=> "TRANSMISSORA ALIANCA DE - ON"]);
             Stock::create(["symbol"=> "TIMS3", "name"=> "TIM SA"]);
             Stock::create(["symbol"=> "TIMP3", "name"=> "TIM PART SA"]);
             Stock::create(["symbol"=> "BOAS3", "name"=> "BOA VISTA SERVICOS SA"]);
             Stock::create(["symbol"=> "CSAB3", "name"=> "CIA SEGUROS ALIANCA DA BAHIA"]);
             Stock::create(["symbol"=> "SEER3", "name"=> "SER EDUCACIONAL SA"]);
             Stock::create(["symbol"=> "SMTO3", "name"=> "SAO MARTINHO SA"]);
             Stock::create(["symbol"=> "BIDI3", "name"=> "BANCO INTER SA - ORD"]);
             Stock::create(["symbol"=> "ECOO11", "name"=> "ISHARES CARBONO EFICIENTE"]);
             Stock::create(["symbol"=> "MOAR3", "name"=> "MONTEIRO ARANHA S.A."]);
             Stock::create(["symbol"=> "LIPR3", "name"=> "ELETROBRAS PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "RAIL3", "name"=> "RUMO SA"]);
             Stock::create(["symbol"=> "RPMG3", "name"=> "REFINARIA DE PETROLEOS MANGU"]);
             Stock::create(["symbol"=> "SBSP3", "name"=> "CIA SANEAMENTO BASICO DE SP"]);
             Stock::create(["symbol"=> "WLMM3", "name"=> "WLM INDUSTRIA E COMERCIO SA"]);
             Stock::create(["symbol"=> "BKBR3", "name"=> "BK BRASIL OPERACAO E ASSESSO"]);
             Stock::create(["symbol"=> "RNEW11", "name"=> "RENOVA ENERGIA SA-UNITS"]);
             Stock::create(["symbol"=> "EZTC3", "name"=> "EZ TEC EMPREENDIMENTOS E PAR"]);
             Stock::create(["symbol"=> "CEAB3", "name"=> "C&A MODAS LTDA"]);
             Stock::create(["symbol"=> "SEQL3", "name"=> "SEQUOIA LOGISTICA E TRANSPOR"]);
             Stock::create(["symbol"=> "DIVO11", "name"=> "IT NOW IDIV FUNDO DE INDICE"]);
             Stock::create(["symbol"=> "ODPV3", "name"=> "ODONTOPREV S.A."]);
             Stock::create(["symbol"=> "FHER3", "name"=> "FERTILIZANTES HERINGER LTDA"]);
             Stock::create(["symbol"=> "PDGR3", "name"=> "PDG REALTY SA"]);
             Stock::create(["symbol"=> "ENJU3", "name"=> "ENJOEI.COM.BR ATIVIDADES DE"]);
             Stock::create(["symbol"=> "BIOM9", "name"=> "BIOMM SA - RCT"]);
             Stock::create(["symbol"=> "RDNI3", "name"=> "RNI NEGOCIOS IMOBILIARIOS SA"]);
             Stock::create(["symbol"=> "UNIP3", "name"=> "UNIPAR CARBOCLORO SA-ORD"]);
             Stock::create(["symbol"=> "ITUB3", "name"=> "ITAU UNIBANCO HOLDING SA"]);
             Stock::create(["symbol"=> "ITUB4", "name"=> "ITAU UNIBANCO HOLDING SA PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "DTCY3", "name"=> "DTCOM-DIRECT TO COMPANY SA"]);
             Stock::create(["symbol"=> "FNCN3", "name"=> "FINANSINOS SA"]);
             Stock::create(["symbol"=> "STKF3", "name"=> "STATKRAFT ENERGIAS RENOVAVEI"]);
             Stock::create(["symbol"=> "VSPT3", "name"=> "FERROVIA CENTRO-ATLANTICA SA"]);
             Stock::create(["symbol"=> "PCAR3", "name"=> "CIA BRASILEIRA DE DISTRIBUIC"]);
             Stock::create(["symbol"=> "PCAR4", "name"=> "CIA BRASILEIRA DE DISTRIBUIC PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "INEP3", "name"=> "INEPAR SA INDUSTRIA E CONSTR"]);
             Stock::create(["symbol"=> "PINE3", "name"=> "BANCO PINE SA"]);
             Stock::create(["symbol"=> "MMXM3", "name"=> "MMX MINERACAO E METALICOS SA"]);
             Stock::create(["symbol"=> "IGTA3", "name"=> "IGUATEMI EMP DE SHOPPING"]);
             Stock::create(["symbol"=> "KLBN3", "name"=> "KLABIN SA"]);
             Stock::create(["symbol"=> "PLAS3", "name"=> "PLASCAR PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "CTKA3", "name"=> "KARSTEN SA"]);
             Stock::create(["symbol"=> "PDTC3", "name"=> "PADTEC HOLDING SA"]);
             Stock::create(["symbol"=> "QUAL3", "name"=> "QUALICORP CONS E CORR SEG SA"]);
             Stock::create(["symbol"=> "XBOV11", "name"=> "CAIXA ETF IBOVESPA FI"]);
             Stock::create(["symbol"=> "TESA3", "name"=> "TERRA SANTA AGRO SA"]);
             Stock::create(["symbol"=> "MGLU3", "name"=> "MAGAZINE LUIZA SA"]);
             Stock::create(["symbol"=> "WIZS3", "name"=> "WIZ SOLUCOES E CORRETAGEM DE"]);
             Stock::create(["symbol"=> "CAML3", "name"=> "CAMIL ALIMENTOS SA"]);
             Stock::create(["symbol"=> "KLBN11", "name"=> "KLABIN SA - UNIT"]);
             Stock::create(["symbol"=> "MDNE3", "name"=> "MOURA DUBEUX ENGENHARIA S/A"]);
             Stock::create(["symbol"=> "AERI3", "name"=> "AERIS INDUSTRIA E COMERCIO D"]);
             Stock::create(["symbol"=> "LUPA3", "name"=> "LUPATECH SA"]);
             Stock::create(["symbol"=> "SQIA3", "name"=> "SINQIA SA"]);
             Stock::create(["symbol"=> "BRDT3", "name"=> "PETROBRAS DISTRIBUIDORA SA"]);
             Stock::create(["symbol"=> "LMED3", "name"=> "LIFEMED INDUSTRIAL DE EQUIPA"]);
             Stock::create(["symbol"=> "LJQQ3", "name"=> "LOJAS QUERO QUERO S/A"]);
             Stock::create(["symbol"=> "IB5M11", "name"=> "IT NOW IB5M"]);
             Stock::create(["symbol"=> "JBDU3", "name"=> "INDUSTRIAS J B DUARTE SA"]);
             Stock::create(["symbol"=> "BSLI3", "name"=> "BRB BANCO DE BRASILIA SA"]);
             Stock::create(["symbol"=> "APER3", "name"=> "ALPER CONSULTORIA E CORRETOR"]);
             Stock::create(["symbol"=> "BAZA3", "name"=> "BANCO DA AMAZONIA SA"]);
             Stock::create(["symbol"=> "PETR3", "name"=> "PETROBRAS - PETROLEO BRAS"]);
             Stock::create(["symbol"=> "PETR4", "name"=> "PETROBRAS - PETROLEO BRAS PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "OMGE3", "name"=> "OMEGA GERACAO SA"]);
             Stock::create(["symbol"=> "IGSN3", "name"=> "IGUA SA"]);
             Stock::create(["symbol"=> "SAPR3", "name"=> "CIA DE SANEAMENTO DO PARANA"]);
             Stock::create(["symbol"=> "CSMG3", "name"=> "CIA SANEAMENTO MINAS GERAIS"]);
             Stock::create(["symbol"=> "CSRN3", "name"=> "CIA ENERGETICA DO RIO GRANDE"]);
             Stock::create(["symbol"=> "MOVI3", "name"=> "MOVIDA PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "CGRA3", "name"=> "GRAZZIOTIN SA"]);
             Stock::create(["symbol"=> "BMOB3", "name"=> "BEMOBI MOBILE TECH SA"]);
             Stock::create(["symbol"=> "CEBR3", "name"=> "CIA ENERGETICA DE BRASILIA"]);
             Stock::create(["symbol"=> "VIVA3", "name"=> "VIVARA PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "SANB11", "name"=> "BANCO SANTANDER  BRASIL-UNIT"]);
             Stock::create(["symbol"=> "COGN3", "name"=> "COGNA EDUCACAO"]);
             Stock::create(["symbol"=> "VIVT3", "name"=> "TELEFONICA BRASIL S.A."]);
             Stock::create(["symbol"=> "VIVT4", "name"=> "TELEFONICA BRASIL S.A. PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "GUAR3", "name"=> "GUARARAPES CONFECCOES SA"]);
             Stock::create(["symbol"=> "RLOG3", "name"=> "COSAN LOGISTICA SA"]);
             Stock::create(["symbol"=> "IRFM11", "name"=> "IT NOW IRF-M"]);
             Stock::create(["symbol"=> "B5P211", "name"=> "IT NOW ETF IMA-B5 P2"]);
             Stock::create(["symbol"=> "STBP3", "name"=> "SANTOS BRASIL PARTICIPACOES"]);
             Stock::create(["symbol"=> "MBLY3", "name"=> "MOBLY SA"]);
             Stock::create(["symbol"=> "CESP3", "name"=> "CIA ENERGETICA DE SAO PAULO"]);
             Stock::create(["symbol"=> "RNEW3", "name"=> "RENOVA ENERGIA SA"]);
             Stock::create(["symbol"=> "COCE3", "name"=> "CIA ENERGETICA DO CEARA"]);
             Stock::create(["symbol"=> "ODER3", "name"=> "CONSERVAS ODERICH SA"]);
             Stock::create(["symbol"=> "ALUP3", "name"=> "ALUPAR INVESTIMENTO SA"]);
             Stock::create(["symbol"=> "CORR3", "name"=> "CORREA RIBEIRO S.A."]);
             Stock::create(["symbol"=> "GMAT3", "name"=> "GRUPO MATEUS SA"]);
             Stock::create(["symbol"=> "MATB11", "name"=> "IT NOW IMAT FUNDO DE INDICE"]);
             Stock::create(["symbol"=> "SLED3", "name"=> "SARAIVA SA-LIVREIROS EDITORE"]);
             Stock::create(["symbol"=> "MGEL3", "name"=> "MANGELS INDUSTRIAL SA"]);
             Stock::create(["symbol"=> "OIBR3", "name"=> "OI SA"]);
             Stock::create(["symbol"=> "POMO3", "name"=> "MARCOPOLO SA"]);
             Stock::create(["symbol"=> "BOVB11", "name"=> "ETF BRADESCO IBOVESPA FI"]);
             Stock::create(["symbol"=> "PETZ3", "name"=> "PET CENTER COMERCIO E PARTIC"]);
             Stock::create(["symbol"=> "MRFG3", "name"=> "MARFRIG GLOBAL FOODS SA"]);
             Stock::create(["symbol"=> "EMAE3", "name"=> "EMPRESA METROPOLITANA DE AGU"]);
             Stock::create(["symbol"=> "BRSR3", "name"=> "BANCO ESTADO RIO GRANDE SUL"]);
             Stock::create(["symbol"=> "BIDI11", "name"=> "BANCO INTER SA-UNITS"]);
             Stock::create(["symbol"=> "SULA3", "name"=> "SUL AMERICA SA"]);
             Stock::create(["symbol"=> "TGMA3", "name"=> "TEGMA GESTAO LOGISTICA"]);
             Stock::create(["symbol"=> "SMFT3", "name"=> "SMARTFIT - ORDINARY"]);
             Stock::create(["symbol"=> "BPAC11", "name"=> "BANCO BTG PACTUAL SA-UNIT"]);
             Stock::create(["symbol"=> "RCSL3", "name"=> "RECRUSUL SA"]);
             Stock::create(["symbol"=> "RPAD3", "name"=> "ALFA HOLDINGS SA"]);
             Stock::create(["symbol"=> "CASN3", "name"=> "CIA CATARINENSE AGUAS SANEAM"]);
             Stock::create(["symbol"=> "CSNA3", "name"=> "CIA SIDERURGICA NACIONAL SA"]);
             Stock::create(["symbol"=> "LAVV3", "name"=> "LAVVI EMPREENDIMENTOS IMOBIL"]);
             Stock::create(["symbol"=> "BALM3", "name"=> "BAUMER SA"]);
             Stock::create(["symbol"=> "BPAC9", "name"=> "BANCO BTG PACTUAL SA CMN-RCP"]);
             Stock::create(["symbol"=> "BGIP3", "name"=> "BANCO ESTADO DE SERGIPE S.A."]);
             Stock::create(["symbol"=> "GEPA3", "name"=> "DUKE ENERGY INTL GERACAO PAR"]);
             Stock::create(["symbol"=> "BRAX11", "name"=> "ISHARES BOVESPA IBRX"]);
             Stock::create(["symbol"=> "WEGE3", "name"=> "WEG SA"]);
             Stock::create(["symbol"=> "DMVF3", "name"=> "D1000 VAREJO FARMA PARTICIPA"]);
             Stock::create(["symbol"=> "ACWI11", "name"=> "TREND ETF ACWI"]);
             Stock::create(["symbol"=> "HAGA3", "name"=> "HAGA SA INDUSTRIA E COMERCIO"]);
             Stock::create(["symbol"=> "CRIV3", "name"=> "FINANCEIRA ALFA SA"]);
             Stock::create(["symbol"=> "BNBR3", "name"=> "BANCO NORDESTE DO BRASIL SA"]);
             Stock::create(["symbol"=> "LREN3", "name"=> "LOJAS RENNER S.A."]);
             Stock::create(["symbol"=> "CNTO3", "name"=> "GRUPO SBF SA"]);
             Stock::create(["symbol"=> "ECPR3", "name"=> "EMP NACL COM REDITO E PART"]);
             Stock::create(["symbol"=> "MNPR3", "name"=> "MINUPAR PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "HBTS3", "name"=> "CIA HABITASUL DE PARTICIPACO"]);
             Stock::create(["symbol"=> "CRPG3", "name"=> "CRISTAL PIGMENTOS DO BRASIL"]);
             Stock::create(["symbol"=> "BRAP3", "name"=> "BRADESPAR SA"]);
             Stock::create(["symbol"=> "BRAP4", "name"=> "BRADESPAR SA PREFERENCE SHARES"]);
             Stock::create(["symbol"=> "LEVE3", "name"=> "MAHLE-METAL LEVE SA"]);
             Stock::create(["symbol"=> "DMMO9", "name"=> "DOMMO ENERGIA SA - RCPT"]);
             Stock::create(["symbol"=> "RADL3", "name"=> "RAIA DROGASIL SA"]);
             Stock::create(["symbol"=> "KEPL3", "name"=> "KEPLER WEBER SA"]);
             Stock::create(["symbol"=> "DMMO3", "name"=> "DOMMO ENERGIA SA"]);
             Stock::create(["symbol"=> "PLPL3", "name"=> "PLANO & PLANO DESENVOLVIMENT"]);
             Stock::create(["symbol"=> "RSID3", "name"=> "ROSSI RESIDENCIAL SA"]);
             Stock::create(["symbol"=> "CYRE3", "name"=> "CYRELA BRAZIL REALTY SA EMP"]);
             Stock::create(["symbol"=> "VAMO3", "name"=> "VAMOS LOCACAO DE CAMINHOES M"]);
             Stock::create(["symbol"=> "AGRO3", "name"=> "BRASILAGRO-CIA BRASILEIRA DE"]);
             Stock::create(["symbol"=> "ORVR3", "name"=> "ORIZON VALORIZACAO DE RESIDU"]);
             Stock::create(["symbol"=> "SMLS3", "name"=> "SMILES FIDELIDADE SA"]);
             Stock::create(["symbol"=> "AVLL3", "name"=> "ALPHAVILLE SA"]);
             Stock::create(["symbol"=> "MTIG3", "name"=> "METALGRAFICA IGUACU SA"]);
             Stock::create(["symbol"=> "PTCA3", "name"=> "PRATICA KLIMAQUIP IND E COM"]);
             Stock::create(["symbol"=> "GOLD11", "name"=> "TREND ETF LBMA OURO"]);
             Stock::create(["symbol"=> "ALPA3", "name"=> "ALPARGATAS SA"]);
             Stock::create(["symbol"=> "POSI3", "name"=> "POSITIVO TECNOLOGIA SA"]);
             Stock::create(["symbol"=> "ISUS11", "name"=> "IT NOW ISE FUNDO DE INDICE"]);
             Stock::create(["symbol"=> "EVEN3", "name"=> "EVEN CONSTRUTORA E INCORPORA"]);
             Stock::create(["symbol"=> "BBOV11", "name"=> "BB ETF IBOVESPA FUNDO DE IND"]);
             Stock::create(["symbol"=> "BTOW3", "name"=> "B2W CIA DIGITAL"]);
             Stock::create(["symbol"=> "TXRX3", "name"=> "TEXTIL RENAUXVIEW SA"]);
             Stock::create(["symbol"=> "PARD3", "name"=> "INSTITUTO HERMES PARDINI SA"]);
             Stock::create(["symbol"=> "FRAS3", "name"=> "FRAS-LE SA"]);
             Stock::create(["symbol"=> "SCAR3", "name"=> "SAO CARLOS EMPREENDIMENTOS"]);
             Stock::create(["symbol"=> "BOVA11", "name"=> "ISHARES IBOVESPA"]);
             Stock::create(["symbol"=> "PTNT3", "name"=> "PETTENATI SA INDUSTRIA TEXTI"]);
             Stock::create(["symbol"=> "JALL3", "name"=> "JALLES MACHADO SA"]);
             Stock::create(["symbol"=> "MWET3", "name"=> "WETZEL SA"]);
             Stock::create(["symbol"=> "MEAL3", "name"=> "INTERNATIONAL MEAL COMPANY A"]);
             Stock::create(["symbol"=> "TEND3", "name"=> "CONSTRUTORA TENDA SA"]);
             Stock::create(["symbol"=> "BTTL3", "name"=> "BATTISTELLA ADM PART SA"]);
             Stock::create(["symbol"=> "LWSA3", "name"=> "LOCAWEB SERVICOS DE INTERNET"]);
             Stock::create(["symbol"=> "SANB3", "name"=> "BANCO SANTANDER (BRASIL) SA"]);
             Stock::create(["symbol"=> "ANIM3", "name"=> "ANIMA HOLDING SA"]);
             Stock::create(["symbol"=> "FIND11", "name"=> "IT NOW IFNC FUNDO DE INDICE"]);
             Stock::create(["symbol"=> "POWE3", "name"=> "FOCUS ENERGIA HOLDING PARTIC"]);
             Stock::create(["symbol"=> "B5MB11", "name"=> "ETF BRADESCO IMA-B5+ FUNDO D"]);
             Stock::create(["symbol"=> "BAUH3", "name"=> "EXCELSIOR ALIMENTOS SA"]);
             Stock::create(["symbol"=> "TCSA3", "name"=> "TECNISA SA"]);
             Stock::create(["symbol"=> "MERC3", "name"=> "MERCANTIL BRASIL FINANCEIRA"]);
             Stock::create(["symbol"=> "LTAM11", "name"=> "CIA INVEST LATINOAMER-DVD CM"]);
             Stock::create(["symbol"=> "MYPK3", "name"=> "IOCHPE-MAXION S.A."]);
             Stock::create(["symbol"=> "BRCR11", "name"=> "FII BTG PACTUAL CORP OFFICE"]);
             Stock::create(["symbol"=> "HBSA3", "name"=> "HIDROVIAS DO BRASIL SA"]);
             Stock::create(["symbol"=> "TUPY3", "name"=> "TUPY SA"]);
             Stock::create(["symbol"=> "PMAM3", "name"=> "PARANAPANEMA S.A."]);
             Stock::create(["symbol"=> "BPAC13", "name"=> "BANCO BTG PACTUAL SA-UN-RCP"]);
             Stock::create(["symbol"=> "NTCO3", "name"=> "NATURA &CO HOLDING SA"]);
             Stock::create(["symbol"=> "EUCA3", "name"=> "EUCATEX SA INDUSTRIA E COMER"]);
             Stock::create(["symbol"=> "SNSY3", "name"=> "SANSUY SA INDUSTRIA DE PLAST"]);
             Stock::create(["symbol"=> "SOND3", "name"=> "SONDOTECNICA ENGENHARIA SOLO"]);
             Stock::create(["symbol"=> "MOSI3", "name"=> "MOSAICO TECNOLOGIA AO CONSUM"]);
             Stock::create(["symbol"=> "MDIA3", "name"=> "M DIAS BRANCO SA"]);
             Stock::create(["symbol"=> "TVIT3", "name"=> "TIVIT TERCEIRIZACAO DE PROCE"]);
             Stock::create(["symbol"=> "CFLP3", "name"=> "CFL INC PAR S/A"]);
             Stock::create(["symbol"=> "LOGN3", "name"=> "LOG-IN LOGISTICA INTERMODAL"]);
             Stock::create(["symbol"=> "RRRP3", "name"=> "3R PETROLEUM OLEO E GAS SA"]);
             Stock::create(["symbol"=> "TRIS3", "name"=> "TRISUL SA"]);
             Stock::create(["symbol"=> "AZEV3", "name"=> "AZEVEDO E TRAVASSOS SA"]);
             Stock::create(["symbol"=> "SPXI11", "name"=> "IT NOW S&P500 TRN FI"]);
             Stock::create(["symbol"=> "CSAN3", "name"=> "COSAN SA"]);
             Stock::create(["symbol"=> "BPAR3", "name"=> "BANCO ESTADO DO PARA S.A."]);
             Stock::create(["symbol"=> "CSED3", "name"=> "CRUZEIRO DO SUL EDUCACIONAL"]);
             Stock::create(["symbol"=> "APTI3", "name"=> "SIDERURGICA J.L. ALIPERTI SA"]);
             Stock::create(["symbol"=> "UCAS3", "name"=> "UNICASA INDUSTRIA DE MOVEIS"]);
             Stock::create(["symbol"=> "CPFE3", "name"=> "CPFL ENERGIA SA"]);
             Stock::create(["symbol"=> "MSPA3", "name"=> "CIA MELHORAMENTOS DE SAO PAU"]);
             Stock::create(["symbol"=> "RDOR3", "name"=> "REDE D'OR SAO LUIZ SA"]);
             Stock::create(["symbol"=> "BBAS3", "name"=> "BANCO DO BRASIL S.A."]);
             Stock::create(["symbol"=> "BRKM3", "name"=> "BRASKEM SA"]);
             Stock::create(["symbol"=> "BRKM5", "name"=> "BRASKEM SAPREFERENCE SHARES"]);
             Stock::create(["symbol"=> "XINA11", "name"=> "ETF TREND MSCI CHINA"]);
             Stock::create(["symbol"=> "GRND3", "name"=> "GRENDENE SA"]);
             Stock::create(["symbol"=> "TECN3", "name"=> "TECHNOS SA"]);
             Stock::create(["symbol"=> "HBOR3", "name"=> "HELBOR EMPREENDIMENTOS SA"]);
             Stock::create(["symbol"=> "MRVE3", "name"=> "MRV ENGENHARIA"]);
             Stock::create(["symbol"=> "ENEV3", "name"=> "ENEVA SA"]);
             Stock::create(["symbol"=> "IVVB11", "name"=> "ISHARES S&P 500 FIC FI IE"]);
             Stock::create(["symbol"=> "RANI3", "name"=> "IRANI SA"]);
             Stock::create(["symbol"=> "MTSA3", "name"=> "METISA METALURGICA TIMBOENSE"]);
             Stock::create(["symbol"=> "ENBR3", "name"=> "EDP - ENERGIAS DO BRASIL SA"]);
             Stock::create(["symbol"=> "RAPT3", "name"=> "RANDON SA IMPLEMENTOS E PART"]);
             Stock::create(["symbol"=> "IMBB11", "name"=> "ETF BRADESCO IMA-B FUNDO DE"]);
             Stock::create(["symbol"=> "DIRR3", "name"=> "DIRECIONAL ENGENHARIA SA"]);
             Stock::create(["symbol"=> "GPCP3", "name"=> "GPC PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "PGMN3", "name"=> "EMPREENDIMENTOS PAGUE MENOS"]);
             Stock::create(["symbol"=> "PPLA11", "name"=> "PPLA PARTICIPATIONS LTD"]);
             Stock::create(["symbol"=> "JHSF3", "name"=> "JHSF PARTICIPACOES SA"]);
             Stock::create(["symbol"=> "VULC3", "name"=> "VULCABRAS AZALEIA SA"]);
             Stock::create(["symbol"=> "ETER9", "name"=> "ETERNIT SA -RCT"]);
             Stock::create(["symbol"=> "BMEB3", "name"=> "BANCO MERCANTIL DO BRASIL SA"]);
             Stock::create(["symbol"=> "ENAT3", "name"=> "ENAUTA PARTICIPACOES SA"]);

             
    }
}
