<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Stock;

class StocksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Stock::create(["symbol" => "AZUL4", "name" => "AZUL SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "GOLL4", "name" => "GOL LINHAS AEREAS", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "CEPE3", "name" => "CIA ENERGETICA DE PERNAMBUCO", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "LAME3", "name" => "LOJAS AMERICANAS SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "LAME4", "name" => "LOJAS AMERICANAS SA PREFERENCE SHARES", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "ALSO3", "name" => "ALIANSCE SONAE SHOPPING CENT", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "OPCT3", "name" => "OCEANPACT SERVICOS MARITIMOS", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "ESTR3", "name" => "MANUF BRINQUEDOS ESTRELA SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "BMKS3", "name" => "BICICLETAS MONARK SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "EQPA3", "name" => "EQUATORIAL PARA DISTRIBUIDOR", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "NORD3", "name" => "NORDON INDUS METALURGICA SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "TIET11", "name" => "AES TIETE ENERGIA SA-UNIT", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "IGBR3", "name" => "IGB ELETRONICA SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "JFEN3", "name" => "JOAO FORTES ENGENHARIA S.A.", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "ROMI3", "name" => "INDUSTRIAS ROMI SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "ECOR3", "name" => "ECORODOVIAS INFRA E LOG SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "TIET3", "name" => "AES TIETE ENERGIA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "PRIO3", "name" => "PETRO RIO SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "ITSA3", "name" => "ITAUSA SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "ITSA4", "name" => "ITAUSA SA PREFERENCE SHARES", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "RENT3", "name" => "LOCALIZA RENT A CAR", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "LUXM3", "name" => "TREVISA INVESTIMENTOS SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "LOGG3", "name" => "LOG COMMERCIAL PROPERTIES E", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "ENGI11", "name" => "ENERGISA SA-UNITS", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CIEL3", "name" => "CIELO SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "JSLG3", "name" => "JSL SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "B3SA3", "name" => "B3 SA-BRASIL BOLSA BALCAO", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "PTBL3", "name" => "PORTOBELLO SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "WHRL3", "name" => "WHIRLPOOL SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "TAEE11", "name" => "TRANSMISSORA ALIANCA DE-UNIT", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "ABEV3", "name" => "AMBEV SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "TEKA3", "name" => "TEKA-TECELAGEM KUEHNRICH SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "CRFB3", "name" => "CARREFOUR BR", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "BRML3", "name" => "BR MALLS PARTICIPACOES SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "GOAU3", "name" => "METALURGICA GERDAU SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "GOAU4", "name" => "METALURGICA GERDAU SA PREFERENCE SHARES", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "VLID3", "name" => "VALID SOLUCOES SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "MULT3", "name" => "MULTIPLAN EMPREENDIMENTOS", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "TPIS3", "name" => "TPI - TRIUNFO PARTICIPACOES", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "ENGI3", "name" => "ENERGISA S.A.", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "MNDL3", "name" => "MUNDIAL SA PROD DE CONSUMO", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "NEMO3", "name" => "SUZANO HOLDING SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "BDLL3", "name" => "BARDELLA SA INDUSTRIAS MECAN", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "FLRY3", "name" => "FLEURY SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "REDE3", "name" => "REDE ENERGIA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "EALT3", "name" => "ELECTRO ACO ALTONA SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "ALPK3", "name" => "ALLPARK EMPREENDIMENTOS PART", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "SHOW3", "name" => "T4F ENTRETENIMENTO SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CTSA3", "name" => "CIA TECIDOS SANTANENSE", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "FESA3", "name" => "FERBASA-FERRO LIGAS DA BAHIA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "INTB3", "name" => "INTELBRAS SA INDUSTRIA DE TE", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "TCNO3", "name" => "TECNOSOLO ENGENHARIA SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "BSEV3", "name" => "BIOSEV SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "GFSA3", "name" => "GAFISA SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "PEAB3", "name" => "CIA PARTICIP ALIANCA BAHIA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "PATI3", "name" => "PANATLANTICA SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "OSXB3", "name" => "OSX BRASIL SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "HBRE3", "name" => "HBR REALTY EMPREENDIMENTOS I", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "PNVL3", "name" => "DIMED SA DISTRIBUIDORA DE ME", "sector" => "Saúde"]);
        Stock::create(["symbol" => "OFSA3", "name" => "OURO FINO SAUDE ANIMAL PARTI", "sector" => "Saúde"]);
        Stock::create(["symbol" => "LLIS3", "name" => "RESTOQUE COMERCIO E CONFEC", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CAMB3", "name" => "CAMBUCI S.A.", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "AMBP3", "name" => "AMBIPAR PARTICIPACOES E EMPR", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "HGTX3", "name" => "CIA HERING", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "JOPA3", "name" => "JOAQUIM OLIVEIRA S.A.-PARTIC", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "BBSD11", "name" => "BB ETF S&P DIVIDENDOS BRASIL", "sector" => "Outros"]);
        Stock::create(["symbol" => "BEES3", "name" => "BANESTES SA-BANCO ESTADO ESP", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "GSHP3", "name" => "GENERAL SHOPPING E OUTLETS D", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "GPAR3", "name" => "CIA CELG DE PARTICIPACOES SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CPLE3", "name" => "CIA PARANAENSE DE ENERGIA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CMIN3", "name" => "CSN MINERACAO SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "CCRO3", "name" => "CCR SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "ALUP11", "name" => "ALUPAR INVESTIMENTO SA-UNIT", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CASH3", "name" => "MELIUZ SA - ON", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "ARZZ3", "name" => "AREZZO INDUSTRIA E COMERCIO", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "LINX3", "name" => "LINX SA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "BRGE3", "name" => "CONSORCIO ALFA DE ADMINIST", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "NGRD3", "name" => "NEOGRID PARTICIPACOES SA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "SULA11", "name" => "SUL AMERICA SA - UNITS", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "AALR3", "name" => "CENTRO DE IMAGEM DIAGNOSTICO", "sector" => "Saúde"]);
        Stock::create(["symbol" => "JPSA3", "name" => "JEREISSATI PARTICIPACOES SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "USIM3", "name" => "USINAS SIDERURGICAS DE MINAS", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "USIM5", "name" => "USINAS SIDERURGICAS DE MINAS PREFERENCE SHARES", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "CVCB3", "name" => "CVC BRASIL OPERADORA E AGENC", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "HAPV3", "name" => "HAPVIDA PARTICIPACOES E INVE", "sector" => "Saúde"]);
        Stock::create(["symbol" => "YDUQ3", "name" => "YDUQS PARTICIPACOES SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "TRPL3", "name" => "CIA DE TRANSMISSAO DE ENERGI", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "PIBB11", "name" => "IT NOW PIBB IBRX-50 FI", "sector" => "Outros"]);
        Stock::create(["symbol" => "BAHI3", "name" => "BAHEMA SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CRDE3", "name" => "CR2 EMPREENDIMENTOS IMOBILIA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "JBSS3", "name" => "JBS SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "MILS3", "name" => "MILLS ESTRUTURAS E SERVICOS", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "LCAM3", "name" => "COMPANHIA DE LOCACAO DAS AME", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "EGIE3", "name" => "ENGIE BRASIL ENERGIA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "HYPE3", "name" => "HYPERA SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "CBEE3", "name" => "AMPLA ENERGIA E SERVICOS SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "DTEX3", "name" => "DURATEX SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "MAPT3", "name" => "CEMEPE INVESTIMENTOS S.A.", "sector" => "Outros"]);
        Stock::create(["symbol" => "BRIV3", "name" => "BANCO ALFA DE INVESTIMENTO", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BIOM3", "name" => "BIOMM SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "DOHL3", "name" => "DOHLER SA COMERCIO E INDUSTR", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "LIGT3", "name" => "LIGHT SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "VVAR3", "name" => "VIA VAREJO SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "TOTS3", "name" => "TOTVS SA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "BBSE3", "name" => "BB SEGURIDADE PARTICIPACOES", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "LPSB3", "name" => "LPS BRASIL CONS DE IMOVEIS", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "TKNO3", "name" => "TEKNO SA INDUSTRIA E COMERCI", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "CEEB3", "name" => "CIA ELETRICIDADE DA BAHIA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "EEEL3", "name" => "CIA ESTADUAL DE GERACAO E TR", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "BPAC3", "name" => "BANCO BTG PACTUAL SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "AHEB3", "name" => "SAO PAULO TURISMO SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "SOMA3", "name" => "GRUPO DE MODA SOMA SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "SGPS3", "name" => "SPRINGS GLOBAL PARTICIPACOES", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "SIMH3", "name" => "SIMPAR SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CNSY3", "name" => "CINESYSTEM SA", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "GGBR3", "name" => "GERDAU S.A.", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "GGBR4", "name" => "GERDAU S.A. PREFERENCE SHARES", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "ENMT3", "name" => "ENERGISA MATO GROSSO DISTRIB", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "TELB3", "name" => "TELECOMUNIC BRASILEIRAS S.A.", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "CEGR3", "name" => "CIA DISTRIBUIDORA DE GAS", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CGAS3", "name" => "CIA DE GAS DE SAO PAULO", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CATA3", "name" => "CIA INDUSTRIAL CATAGUASES", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "PSSA3", "name" => "PORTO SEGURO SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "ESPA3", "name" => "MPM CORPOREOS SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "TASA3", "name" => "TAURUS ARMAS", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "GNDI3", "name" => "NOTRE DAME INTERMED PAR SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "WEST3", "name" => "WESTWING COMERCIO VAREJISTA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "BRFS3", "name" => "BRF SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "ELMD3", "name" => "ELETROMIDIA SA", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "BEEF3", "name" => "MINERVA SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "CURY3", "name" => "CURY CONSTRUTORA E INCORPORA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "MTRE3", "name" => "MITRE REALTY EMPREENDIMENTOS", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "PRNR3", "name" => "PRINER SERVICOS INDUSTRIAIS", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "MELK3", "name" => "MELNICK EVEN DESENVOLVIMENTO", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "SLCE3", "name" => "SLC AGRICOLA SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "BBRK3", "name" => "BRASIL BROKERS PARTICIPACOES", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "GOVE11", "name" => "IT NOW IGCT FUNDO DE INDICE", "sector" => "Outros"]);
        Stock::create(["symbol" => "BRPR3", "name" => "BR PROPERTIES SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "EMBR3", "name" => "EMBRAER SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "SUZB3", "name" => "SUZANO SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "BBDC3", "name" => "BANCO BRADESCO S.A.", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BBDC4", "name" => "BANCO BRADESCO S.A. PREFERENCE SHARES", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "DASA3", "name" => "DIAGNOSTICOS DA AMERICA SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "CEED3", "name" => "CIA ESTADUAL DE DISTRIBUICAO", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "ELET3", "name" => "CENTRAIS ELETRICAS BRASILIER", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "ELET6", "name" => "CENTRAIS ELETRICAS BRASILIER PREFERENCE SHARES", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "SMAC11", "name" => "IT NOW ETF SMLL", "sector" => "Outros"]);
        Stock::create(["symbol" => "NEOE3", "name" => "NEOENERGIA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "PFRM3", "name" => "PROFARMA DISTRIBUIDORA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "CTNM3", "name" => "CIA TECIDOS NORTE DE MINAS", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "BMIN3", "name" => "BANCO MERCANTIL DE INVESTIME", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "PSVM11", "name" => "PORTO SUDESTE VM SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "CCPR3", "name" => "CYRELA COMMERCIAL PROPERTIES", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CEDO3", "name" => "CIA DE FIACAO E TECIDOS CEDR", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "HETA3", "name" => "HERCULES SA FABRICA TALHERES", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CLSC3", "name" => "CENTRAIS ELETRICA STA CATARI", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "ETER3", "name" => "ETERNIT SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "AFLT3", "name" => "AFLUENTE TRANSMISSAO DE", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "EKTR3", "name" => "ELEKTRO REDES SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "AMAR3", "name" => "MARISA LOJAS SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "FRIO3", "name" => "METALFRIO SOLUTIONS SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "SAPR11", "name" => "CIA DE SANEAMENTO DO PA-UNIT", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "NUTR3", "name" => "NUTRIPLANT INDUSTRIA E COMER", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "FRTA3", "name" => "POMIFRUTAS SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "SMAL11", "name" => "ISHARES BM&FBOVESPA SM CAP", "sector" => "Outros"]);
        Stock::create(["symbol" => "VIVR3", "name" => "VIVER INCORPORADORA E CONSTR", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "UGPA3", "name" => "ULTRAPAR PARTICIPACOES SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "BOVV11", "name" => "IT NOW IBOVESPA FUNDO INDICE", "sector" => "Outros"]);
        Stock::create(["symbol" => "BPAC12", "name" => "BANCO BTG PACTUAL SA PNA-RCP", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "XFIX11", "name" => "TREND ETF IFIX", "sector" => "Outros"]);
        Stock::create(["symbol" => "IMAB11", "name" => "IT NOW ID ETF IMA-B", "sector" => "Outros"]);
        Stock::create(["symbol" => "RSUL3", "name" => "METALURGICA RIOSULENSE S.A.", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "IRBR3", "name" => "IRB BRASIL RESSEGUROS SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "EQTL3", "name" => "EQUATORIAL ENERGIA SA - ORD", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "VALE3", "name" => "VALE SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "HOOT3", "name" => "HOTEIS OTHON S.A.", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "ATOM3", "name" => "ATOM PARTICIPACOES SA", "sector" => "Outros"]);
        Stock::create(["symbol" => "CARD3", "name" => "CSU CARDSYSTEM SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CMIG3", "name" => "CIA ENERGETICA DE MINAS GER", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CMIG4", "name" => "CIA ENERGETICA DE MINAS GER PREFERENCE SHARES", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "TAEE3", "name" => "TRANSMISSORA ALIANCA DE - ON", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "TIMS3", "name" => "TIM SA", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "TIMP3", "name" => "TIM PART SA", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "BOAS3", "name" => "BOA VISTA SERVICOS SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CSAB3", "name" => "CIA SEGUROS ALIANCA DA BAHIA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "SEER3", "name" => "SER EDUCACIONAL SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "SMTO3", "name" => "SAO MARTINHO SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "BIDI3", "name" => "BANCO INTER SA - ORD", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "ECOO11", "name" => "ISHARES CARBONO EFICIENTE", "sector" => "Outros"]);
        Stock::create(["symbol" => "MOAR3", "name" => "MONTEIRO ARANHA S.A.", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "LIPR3", "name" => "ELETROBRAS PARTICIPACOES SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "RAIL3", "name" => "RUMO SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "RPMG3", "name" => "REFINARIA DE PETROLEOS MANGU", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "SBSP3", "name" => "CIA SANEAMENTO BASICO DE SP", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "WLMM3", "name" => "WLM INDUSTRIA E COMERCIO SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "BKBR3", "name" => "BK BRASIL OPERACAO E ASSESSO", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "RNEW11", "name" => "RENOVA ENERGIA SA-UNITS", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "EZTC3", "name" => "EZ TEC EMPREENDIMENTOS E PAR", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "CEAB3", "name" => "C&A MODAS LTDA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "SEQL3", "name" => "SEQUOIA LOGISTICA E TRANSPOR", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "DIVO11", "name" => "IT NOW IDIV FUNDO DE INDICE", "sector" => "Outros"]);
        Stock::create(["symbol" => "ODPV3", "name" => "ODONTOPREV S.A.", "sector" => "Saúde"]);
        Stock::create(["symbol" => "FHER3", "name" => "FERTILIZANTES HERINGER LTDA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "PDGR3", "name" => "PDG REALTY SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "ENJU3", "name" => "ENJOEI.COM.BR ATIVIDADES DE", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "BIOM9", "name" => "BIOMM SA - RCT", "sector" => "Saúde"]);
        Stock::create(["symbol" => "RDNI3", "name" => "RNI NEGOCIOS IMOBILIARIOS SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "UNIP3", "name" => "UNIPAR CARBOCLORO SA-ORD", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "ITUB3", "name" => "ITAU UNIBANCO HOLDING SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "ITUB4", "name" => "ITAU UNIBANCO HOLDING SA PREFERENCE SHARES", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "DTCY3", "name" => "DTCOM-DIRECT TO COMPANY SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "FNCN3", "name" => "FINANSINOS SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "STKF3", "name" => "STATKRAFT ENERGIAS RENOVAVEI", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "VSPT3", "name" => "FERROVIA CENTRO-ATLANTICA SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "PCAR3", "name" => "CIA BRASILEIRA DE DISTRIBUIC", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "PCAR4", "name" => "CIA BRASILEIRA DE DISTRIBUIC PREFERENCE SHARES", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "INEP3", "name" => "INEPAR SA INDUSTRIA E CONSTR", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "PINE3", "name" => "BANCO PINE SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "MMXM3", "name" => "MMX MINERACAO E METALICOS SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "IGTA3", "name" => "IGUATEMI EMP DE SHOPPING", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "KLBN3", "name" => "KLABIN SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "PLAS3", "name" => "PLASCAR PARTICIPACOES SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CTKA3", "name" => "KARSTEN SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "PDTC3", "name" => "PADTEC HOLDING SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "QUAL3", "name" => "QUALICORP CONS E CORR SEG SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "XBOV11", "name" => "CAIXA ETF IBOVESPA FI", "sector" => "Outros"]);
        Stock::create(["symbol" => "TESA3", "name" => "TERRA SANTA AGRO SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "MGLU3", "name" => "MAGAZINE LUIZA SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "WIZS3", "name" => "WIZ SOLUCOES E CORRETAGEM DE", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CAML3", "name" => "CAMIL ALIMENTOS SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "KLBN11", "name" => "KLABIN SA - UNIT", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "MDNE3", "name" => "MOURA DUBEUX ENGENHARIA S/A", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "AERI3", "name" => "AERIS INDUSTRIA E COMERCIO D", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "LUPA3", "name" => "LUPATECH SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "SQIA3", "name" => "SINQIA SA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "BRDT3", "name" => "PETROBRAS DISTRIBUIDORA SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "LMED3", "name" => "LIFEMED INDUSTRIAL DE EQUIPA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "LJQQ3", "name" => "LOJAS QUERO QUERO S/A", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "IB5M11", "name" => "IT NOW IB5M", "sector" => "Outros"]);
        Stock::create(["symbol" => "JBDU3", "name" => "INDUSTRIAS J B DUARTE SA", "sector" => "Outros"]);
        Stock::create(["symbol" => "BSLI3", "name" => "BRB BANCO DE BRASILIA SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "APER3", "name" => "ALPER CONSULTORIA E CORRETOR", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BAZA3", "name" => "BANCO DA AMAZONIA SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "PETR3", "name" => "PETROBRAS - PETROLEO BRAS", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "PETR4", "name" => "PETROBRAS - PETROLEO BRAS PREFERENCE SHARES", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "OMGE3", "name" => "OMEGA GERACAO SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "IGSN3", "name" => "IGUA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "SAPR3", "name" => "CIA DE SANEAMENTO DO PARANA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CSMG3", "name" => "CIA SANEAMENTO MINAS GERAIS", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CSRN3", "name" => "CIA ENERGETICA DO RIO GRANDE", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "MOVI3", "name" => "MOVIDA PARTICIPACOES SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CGRA3", "name" => "GRAZZIOTIN SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "BMOB3", "name" => "BEMOBI MOBILE TECH SA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "CEBR3", "name" => "CIA ENERGETICA DE BRASILIA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "VIVA3", "name" => "VIVARA PARTICIPACOES SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "SANB11", "name" => "BANCO SANTANDER  BRASIL-UNIT", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "COGN3", "name" => "COGNA EDUCACAO", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "VIVT3", "name" => "TELEFONICA BRASIL S.A.", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "VIVT4", "name" => "TELEFONICA BRASIL S.A. PREFERENCE SHARES", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "GUAR3", "name" => "GUARARAPES CONFECCOES SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "RLOG3", "name" => "COSAN LOGISTICA SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "IRFM11", "name" => "IT NOW IRF-M", "sector" => "Outros"]);
        Stock::create(["symbol" => "B5P211", "name" => "IT NOW ETF IMA-B5 P2", "sector" => "Outros"]);
        Stock::create(["symbol" => "STBP3", "name" => "SANTOS BRASIL PARTICIPACOES", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "MBLY3", "name" => "MOBLY SA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "CESP3", "name" => "CIA ENERGETICA DE SAO PAULO", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "RNEW3", "name" => "RENOVA ENERGIA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "COCE3", "name" => "CIA ENERGETICA DO CEARA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "ODER3", "name" => "CONSERVAS ODERICH SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "ALUP3", "name" => "ALUPAR INVESTIMENTO SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CORR3", "name" => "CORREA RIBEIRO S.A.", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "GMAT3", "name" => "GRUPO MATEUS SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "MATB11", "name" => "IT NOW IMAT FUNDO DE INDICE", "sector" => "Outros"]);
        Stock::create(["symbol" => "SLED3", "name" => "SARAIVA SA-LIVREIROS EDITORE", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "MGEL3", "name" => "MANGELS INDUSTRIAL SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "OIBR3", "name" => "OI SA", "sector" => "Comunicações"]);
        Stock::create(["symbol" => "POMO3", "name" => "MARCOPOLO SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "BOVB11", "name" => "ETF BRADESCO IBOVESPA FI", "sector" => "Outros"]);
        Stock::create(["symbol" => "PETZ3", "name" => "PET CENTER COMERCIO E PARTIC", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "MRFG3", "name" => "MARFRIG GLOBAL FOODS SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "EMAE3", "name" => "EMPRESA METROPOLITANA DE AGU", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "BRSR3", "name" => "BANCO ESTADO RIO GRANDE SUL", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BIDI11", "name" => "BANCO INTER SA-UNITS", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "SULA3", "name" => "SUL AMERICA SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "TGMA3", "name" => "TEGMA GESTAO LOGISTICA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "SMFT3", "name" => "SMARTFIT - ORDINARY", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "BPAC11", "name" => "BANCO BTG PACTUAL SA-UNIT", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "RCSL3", "name" => "RECRUSUL SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "RPAD3", "name" => "ALFA HOLDINGS SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CASN3", "name" => "CIA CATARINENSE AGUAS SANEAM", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "CSNA3", "name" => "CIA SIDERURGICA NACIONAL SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "LAVV3", "name" => "LAVVI EMPREENDIMENTOS IMOBIL", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "BALM3", "name" => "BAUMER SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "BPAC9", "name" => "BANCO BTG PACTUAL SA CMN-RCP", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BGIP3", "name" => "BANCO ESTADO DE SERGIPE S.A.", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "GEPA3", "name" => "DUKE ENERGY INTL GERACAO PAR", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "BRAX11", "name" => "ISHARES BOVESPA IBRX", "sector" => "Outros"]);
        Stock::create(["symbol" => "WEGE3", "name" => "WEG SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "DMVF3", "name" => "D1000 VAREJO FARMA PARTICIPA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "ACWI11", "name" => "TREND ETF ACWI", "sector" => "Outros"]);
        Stock::create(["symbol" => "HAGA3", "name" => "HAGA SA INDUSTRIA E COMERCIO", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "CRIV3", "name" => "FINANCEIRA ALFA SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BNBR3", "name" => "BANCO NORDESTE DO BRASIL SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "LREN3", "name" => "LOJAS RENNER S.A.", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CNTO3", "name" => "GRUPO SBF SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "ECPR3", "name" => "EMP NACL COM REDITO E PART", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "MNPR3", "name" => "MINUPAR PARTICIPACOES SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "HBTS3", "name" => "CIA HABITASUL DE PARTICIPACO", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CRPG3", "name" => "CRISTAL PIGMENTOS DO BRASIL", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "BRAP3", "name" => "BRADESPAR SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "BRAP4", "name" => "BRADESPAR SA PREFERENCE SHARES", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "LEVE3", "name" => "MAHLE-METAL LEVE SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "DMMO9", "name" => "DOMMO ENERGIA SA - RCPT", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "RADL3", "name" => "RAIA DROGASIL SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "KEPL3", "name" => "KEPLER WEBER SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "DMMO3", "name" => "DOMMO ENERGIA SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "PLPL3", "name" => "PLANO & PLANO DESENVOLVIMENT", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "RSID3", "name" => "ROSSI RESIDENCIAL SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "CYRE3", "name" => "CYRELA BRAZIL REALTY SA EMP", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "VAMO3", "name" => "VAMOS LOCACAO DE CAMINHOES M", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "AGRO3", "name" => "BRASILAGRO-CIA BRASILEIRA DE", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "ORVR3", "name" => "ORIZON VALORIZACAO DE RESIDU", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "SMLS3", "name" => "SMILES FIDELIDADE SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "AVLL3", "name" => "ALPHAVILLE SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "MTIG3", "name" => "METALGRAFICA IGUACU SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "PTCA3", "name" => "PRATICA KLIMAQUIP IND E COM", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "GOLD11", "name" => "TREND ETF LBMA OURO", "sector" => "Outros"]);
        Stock::create(["symbol" => "ALPA3", "name" => "ALPARGATAS SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "POSI3", "name" => "POSITIVO TECNOLOGIA SA", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "ISUS11", "name" => "IT NOW ISE FUNDO DE INDICE", "sector" => "Outros"]);
        Stock::create(["symbol" => "EVEN3", "name" => "EVEN CONSTRUTORA E INCORPORA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "BBOV11", "name" => "BB ETF IBOVESPA FUNDO DE IND", "sector" => "Outros"]);
        Stock::create(["symbol" => "BTOW3", "name" => "B2W CIA DIGITAL", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "TXRX3", "name" => "TEXTIL RENAUXVIEW SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "PARD3", "name" => "INSTITUTO HERMES PARDINI SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "FRAS3", "name" => "FRAS-LE SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "SCAR3", "name" => "SAO CARLOS EMPREENDIMENTOS", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BOVA11", "name" => "ISHARES IBOVESPA", "sector" => "Outros"]);
        Stock::create(["symbol" => "PTNT3", "name" => "PETTENATI SA INDUSTRIA TEXTI", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "JALL3", "name" => "JALLES MACHADO SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "MWET3", "name" => "WETZEL SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "MEAL3", "name" => "INTERNATIONAL MEAL COMPANY A", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "TEND3", "name" => "CONSTRUTORA TENDA SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "BTTL3", "name" => "BATTISTELLA ADM PART SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "LWSA3", "name" => "LOCAWEB SERVICOS DE INTERNET", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "SANB3", "name" => "BANCO SANTANDER (BRASIL) SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "ANIM3", "name" => "ANIMA HOLDING SA", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "FIND11", "name" => "IT NOW IFNC FUNDO DE INDICE", "sector" => "Outros"]);
        Stock::create(["symbol" => "POWE3", "name" => "FOCUS ENERGIA HOLDING PARTIC", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "B5MB11", "name" => "ETF BRADESCO IMA-B5+ FUNDO D", "sector" => "Outros"]);
        Stock::create(["symbol" => "BAUH3", "name" => "EXCELSIOR ALIMENTOS SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "TCSA3", "name" => "TECNISA SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "MERC3", "name" => "MERCANTIL BRASIL FINANCEIRA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "LTAM11", "name" => "CIA INVEST LATINOAMER-DVD CM", "sector" => "Outros"]);
        Stock::create(["symbol" => "MYPK3", "name" => "IOCHPE-MAXION S.A.", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "BRCR11", "name" => "FII BTG PACTUAL CORP OFFICE", "sector" => "Outros"]);
        Stock::create(["symbol" => "HBSA3", "name" => "HIDROVIAS DO BRASIL SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "TUPY3", "name" => "TUPY SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "PMAM3", "name" => "PARANAPANEMA S.A.", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "BPAC13", "name" => "BANCO BTG PACTUAL SA-UN-RCP", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "NTCO3", "name" => "NATURA &CO HOLDING SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "EUCA3", "name" => "EUCATEX SA INDUSTRIA E COMER", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "SNSY3", "name" => "SANSUY SA INDUSTRIA DE PLAST", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "SOND3", "name" => "SONDOTECNICA ENGENHARIA SOLO", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "MOSI3", "name" => "MOSAICO TECNOLOGIA AO CONSUM", "sector" => "Tecnologia da Informação"]);
        Stock::create(["symbol" => "MDIA3", "name" => "M DIAS BRANCO SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "TVIT3", "name" => "TIVIT TERCEIRIZACAO DE PROCE", "sector" => "Outros"]);
        Stock::create(["symbol" => "CFLP3", "name" => "CFL INC PAR S/A", "sector" => "Outros"]);
        Stock::create(["symbol" => "LOGN3", "name" => "LOG-IN LOGISTICA INTERMODAL", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "RRRP3", "name" => "3R PETROLEUM OLEO E GAS SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "TRIS3", "name" => "TRISUL SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "AZEV3", "name" => "AZEVEDO E TRAVASSOS SA", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "SPXI11", "name" => "IT NOW S&P500 TRN FI", "sector" => "Outros"]);
        Stock::create(["symbol" => "CSAN3", "name" => "COSAN SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
        Stock::create(["symbol" => "BPAR3", "name" => "BANCO ESTADO DO PARA S.A.", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "CSED3", "name" => "CRUZEIRO DO SUL EDUCACIONAL", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "APTI3", "name" => "SIDERURGICA J.L. ALIPERTI SA", "sector" => "Comércio não Cíclico"]);
        Stock::create(["symbol" => "UCAS3", "name" => "UNICASA INDUSTRIA DE MOVEIS", "sector" => "Consumo Cíclico"]);
        Stock::create(["symbol" => "CPFE3", "name" => "CPFL ENERGIA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "MSPA3", "name" => "CIA MELHORAMENTOS DE SAO PAU", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "RDOR3", "name" => "REDE D'OR SAO LUIZ SA", "sector" => "Saúde"]);
        Stock::create(["symbol" => "BBAS3", "name" => "BANCO DO BRASIL S.A.", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "BRKM3", "name" => "BRASKEM SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "BRKM5", "name" => "BRASKEM SAPREFERENCE SHARES", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "XINA11", "name" => "ETF TREND MSCI CHINA", "sector" => "Outros"]);
        Stock::create(["symbol" => "GRND3", "name" => "GRENDENE SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "TECN3", "name" => "TECHNOS SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "HBOR3", "name" => "HELBOR EMPREENDIMENTOS SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "MRVE3", "name" => "MRV ENGENHARIA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "ENEV3", "name" => "ENEVA SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "IVVB11", "name" => "ISHARES S&P 500 FIC FI IE", "sector" => "Outros"]);
        Stock::create(["symbol" => "RANI3", "name" => "IRANI SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "MTSA3", "name" => "METISA METALURGICA TIMBOENSE", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "ENBR3", "name" => "EDP - ENERGIAS DO BRASIL SA", "sector" => "Utilidade Pública"]);
        Stock::create(["symbol" => "RAPT3", "name" => "RANDON SA IMPLEMENTOS E PART", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "IMBB11", "name" => "ETF BRADESCO IMA-B FUNDO DE", "sector" => "Outros"]);
        Stock::create(["symbol" => "DIRR3", "name" => "DIRECIONAL ENGENHARIA SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "GPCP3", "name" => "GPC PARTICIPACOES SA", "sector" => "Materiais Básicos"]);
        Stock::create(["symbol" => "PGMN3", "name" => "EMPREENDIMENTOS PAGUE MENOS", "sector" => "Saúde"]);
        Stock::create(["symbol" => "PPLA11", "name" => "PPLA PARTICIPATIONS LTD", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "JHSF3", "name" => "JHSF PARTICIPACOES SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "VULC3", "name" => "VULCABRAS AZALEIA SA", "sector" => "Comércio Cíclico"]);
        Stock::create(["symbol" => "ETER9", "name" => "ETERNIT SA -RCT", "sector" => "Bens Industriais"]);
        Stock::create(["symbol" => "BMEB3", "name" => "BANCO MERCANTIL DO BRASIL SA", "sector" => "Financeiro"]);
        Stock::create(["symbol" => "ENAT3", "name" => "ENAUTA PARTICIPACOES SA", "sector" => "Petróleo, Gás e Biocombustíveis"]);
    }
}
